package dsl;
/* Generated By:JavaCC: Do not edit this line. DSLTreeConstants.java Version 5.0 */
public interface DSLTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTDSLATRIBUTION = 2;
  public int JJTTERM = 3;
  public int JJTDSLEXPR = 4;
  public int JJTDSLTERM = 5;
  public int JJTDSLTERMTAIL = 6;
  public int JJTDSLFACTOR = 7;
  public int JJTDSLFACTORTAIL = 8;
  public int JJTDSLEXPR2 = 9;
  public int JJTDSLTERM2 = 10;
  public int JJTDSLTERMTAIL2 = 11;
  public int JJTDSLFACTOR2 = 12;
  public int JJTDSLFACTORTAIL2 = 13;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "dslAtribution",
    "Term",
    "dslExpr",
    "dslTerm",
    "dslTermTail",
    "dslFactor",
    "dslFactorTail",
    "dslExpr2",
    "dslTerm2",
    "dslTermTail2",
    "dslFactor2",
    "dslFactorTail2",
  };
}
/* JavaCC - OriginalChecksum=86164519bd92cb3e4cffcc9f2afc9ffb (do not edit this line) */
