/* Generated By:JJTree&JavaCC: Do not edit this line. DSLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DSLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IN = 5;
  /** RegularExpression Id. */
  int OUT = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int STAR = 9;
  /** RegularExpression Id. */
  int SLASH = 10;
  /** RegularExpression Id. */
  int FLOAT = 11;
  /** RegularExpression Id. */
  int INT = 12;
  /** RegularExpression Id. */
  int DOUBLE = 13;
  /** RegularExpression Id. */
  int LPAREN = 14;
  /** RegularExpression Id. */
  int RPAREN = 15;
  /** RegularExpression Id. */
  int LBRACKET = 16;
  /** RegularExpression Id. */
  int RBRACKET = 17;
  /** RegularExpression Id. */
  int SEMICOLON = 18;
  /** RegularExpression Id. */
  int ASSIGN = 19;
  /** RegularExpression Id. */
  int COLON = 20;
  /** RegularExpression Id. */
  int INTEGER = 21;
  /** RegularExpression Id. */
  int DECIMAL_NUMBER = 22;
  /** RegularExpression Id. */
  int VAR = 23;
  /** RegularExpression Id. */
  int ARROBAMAT = 24;
  /** RegularExpression Id. */
  int LETTERS = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"in\"",
    "\"out\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"float\"",
    "\"int\"",
    "\"double\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"=\"",
    "\":\"",
    "<INTEGER>",
    "<DECIMAL_NUMBER>",
    "<VAR>",
    "\"@mat\"",
    "<LETTERS>",
    "\"/*@mat\"",
    "\"*/\"",
  };

}
