/* Generated By:JavaCC: Do not edit this line. DSLTreeConstants.java Version 5.0 */
public interface DSLTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTDSLATRIBUTION = 2;
  public int JJTTERM = 3;
  public int JJTDSLEXPR = 4;
  public int JJTDSLTERM = 5;
  public int JJTDSLTERMTAIL = 6;
  public int JJTDSLFACTOR = 7;
  public int JJTDSLPARENTESES = 8;
  public int JJTDSLFACTORTAIL = 9;
  public int JJTDSLEXPR2 = 10;
  public int JJTDSLTERM2 = 11;
  public int JJTDSLTERMTAIL2 = 12;
  public int JJTDSLFACTOR2 = 13;
  public int JJTDSLFACTORTAIL2 = 14;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "dslAtribution",
    "Term",
    "dslExpr",
    "dslTerm",
    "dslTermTail",
    "dslFactor",
    "dslParenteses",
    "dslFactorTail",
    "dslExpr2",
    "dslTerm2",
    "dslTermTail2",
    "dslFactor2",
    "dslFactorTail2",
  };
}
/* JavaCC - OriginalChecksum=b32e2c3db5bbb216b23dde8944bd9df2 (do not edit this line) */
